#!/usr/bin/env bash
# Deep-night blues, indigo glow.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="space"
NVIM_COLORSCHEME="rice-space"
STARSHIP_PALETTE="space"

BG="161c29"
BG_DARK="0e1420"
BG_HL="252e40"
FG="cad1e0"
FG_MUTED="8b92a2"
ACCENT="71a3ff"
ACCENT_ALT="bb81f7"

BLACK="323c50"        BRIGHT_BLACK="4f596f"
RED="fc7499"          BRIGHT_RED="ff96af"
GREEN="00c686"        BRIGHT_GREEN="00dc96"
YELLOW="bdd544"       BRIGHT_YELLOW="d0ea4e"
BLUE="77a6ff"         BRIGHT_BLUE="95bbff"
MAGENTA="db7fe1"      BRIGHT_MAGENTA="f28ff9"
CYAN="00cfdf"         BRIGHT_CYAN="00e5f6"
WHITE="b2b9c8"        BRIGHT_WHITE="e0e5ef"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="4b68a2"   BORDER_INACTIVE="1e2635"
SYN_KEYWORD="fc94a6"
SYN_FUNC="80bdf9"
SYN_STRING="6cbf91"
SYN_NUMBER="56cadc"
SYN_TYPE="b8ce90"
SYN_CONST="c2a8f1"
SYN_PROP="bfc5ea"
SYN_COMMENT="727a8d"
SYN_OPERATOR="a6adbc"
SYN_SPECIAL="bb81f7"

# wallpaper gradient stops (dark -> tinted)
WALL0="070c18"; WALL1="161c29"; WALL2="2b3956"; WALL3="2f3659"
