#!/usr/bin/env bash
# Deep-night blues, indigo glow.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="space"
NVIM_COLORSCHEME="rice-space"
STARSHIP_PALETTE="space"

BG="171c26"
BG_DARK="0f141e"
BG_HL="272e3c"
FG="cad1e0"
FG_MUTED="8b92a2"
ACCENT="77a4f6"
ACCENT_ALT="b48de0"

BLACK="343c4d"        BRIGHT_BLACK="51596c"
RED="e9859d"          BRIGHT_RED="ff96af"
GREEN="52c08e"        BRIGHT_GREEN="5cd59f"
YELLOW="bfd371"       BRIGHT_YELLOW="d2e77c"
BLUE="7ca7f6"         BRIGHT_BLUE="95bbff"
MAGENTA="cf8bd3"      BRIGHT_MAGENTA="e69bea"
CYAN="2ecedc"         BRIGHT_CYAN="32e3f3"
WHITE="b2b9c7"        BRIGHT_WHITE="e0e5ef"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="4f699c"   BORDER_INACTIVE="202632"
SYN_KEYWORD="f29ba9"
SYN_FUNC="8cbdec"
SYN_STRING="7bbc97"
SYN_NUMBER="71c7d5"
SYN_TYPE="bbcc9e"
SYN_CONST="c0abe6"
SYN_PROP="c1c6e5"
SYN_COMMENT="727a8d"
SYN_OPERATOR="a6adbb"
SYN_SPECIAL="b48de0"

# wallpaper gradient stops (dark -> tinted)
WALL0="080c16"; WALL1="171c26"; WALL2="252f43"; WALL3="272e42"
