#!/usr/bin/env bash
# Electric blue on near-black.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="techy"
NVIM_COLORSCHEME="rice-techy"
STARSHIP_PALETTE="techy"

BG="0e1216"
BG_DARK="070a0e"
BG_HL="1c242b"
FG="c7d2df"
FG_MUTED="8794a1"
ACCENT="60a7ff"
ACCENT_ALT="d26ffb"

BLACK="29313a"        BRIGHT_BLACK="454e58"
RED="ff7390"          BRIGHT_RED="ff97a9"
GREEN="00c777"        BRIGHT_GREEN="00dd84"
YELLOW="cdd100"       BRIGHT_YELLOW="e1e500"
BLUE="75a7ff"         BRIGHT_BLUE="94bbff"
MAGENTA="e970ea"      BRIGHT_MAGENTA="fe83ff"
CYAN="00d0da"         BRIGHT_CYAN="00e6f1"
WHITE="aeb8c4"        BRIGHT_WHITE="dde6ee"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="3b6798"   BORDER_INACTIVE="161c21"
SYN_KEYWORD="ff91a8"
SYN_FUNC="76beff"
SYN_STRING="58c389"
SYN_NUMBER="1acee3"
SYN_TYPE="b6d07e"
SYN_CONST="c3a4ff"
SYN_PROP="b8c7f0"
SYN_COMMENT="6d7c8c"
SYN_OPERATOR="a1abb6"
SYN_SPECIAL="d26ffb"

# wallpaper gradient stops (dark -> tinted)
WALL0="030507"; WALL1="0e1216"; WALL2="1f3245"; WALL3="202f4d"
