#!/usr/bin/env bash
# Electric blue on near-black.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="techy"
NVIM_COLORSCHEME="rice-techy"
STARSHIP_PALETTE="techy"

BG="0e1216"
BG_DARK="070a0e"
BG_HL="1d232a"
FG="c7d2df"
FG_MUTED="8794a1"
ACCENT="60a7ff"
ACCENT_ALT="c681e4"

BLACK="29313a"        BRIGHT_BLACK="454e58"
RED="f87992"          BRIGHT_RED="ff97a9"
GREEN="3bc47d"        BRIGHT_GREEN="46d98c"
YELLOW="ccd046"       BRIGHT_YELLOW="e0e450"
BLUE="75a7ff"         BRIGHT_BLUE="94bbff"
MAGENTA="da82da"      BRIGHT_MAGENTA="f291f2"
CYAN="00d0da"         BRIGHT_CYAN="00e6f1"
WHITE="aeb8c4"        BRIGHT_WHITE="dde6ee"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="3b6798"   BORDER_INACTIVE="161b21"
SYN_KEYWORD="fc94a9"
SYN_FUNC="7ebef8"
SYN_STRING="6dbf90"
SYN_NUMBER="56cadb"
SYN_TYPE="b9ce8f"
SYN_CONST="c1a8f2"
SYN_PROP="bac7ea"
SYN_COMMENT="6d7c8c"
SYN_OPERATOR="a1abb6"
SYN_SPECIAL="c681e4"

# wallpaper gradient stops (dark -> tinted)
WALL0="030507"; WALL1="0e1216"; WALL2="192735"; WALL3="1b2636"
