#!/usr/bin/env bash
# Hot pink on deep raspberry plum.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="pink"
NVIM_COLORSCHEME="rice-pink"
STARSHIP_PALETTE="pink"

BG="20131d"
BG_DARK="180c15"
BG_HL="352331"
FG="dcccd4"
FG_MUTED="9e8c96"
ACCENT="fb69ab"
ACCENT_ALT="ca7aed"

BLACK="443140"        BRIGHT_BLACK="634d5e"
RED="ff7681"          BRIGHT_RED="ff999e"
GREEN="9fb500"        BRIGHT_GREEN="b1c909"
YELLOW="ffb83c"       BRIGHT_YELLOW="ffd391"
BLUE="959dff"         BRIGHT_BLUE="abb4ff"
MAGENTA="eb78cc"      BRIGHT_MAGENTA="ff8cdf"
CYAN="00cafc"         BRIGHT_CYAN="73daff"
WHITE="c3b3bb"        BRIGHT_WHITE="ece1e7"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="994675"   BORDER_INACTIVE="2b1c28"
SYN_KEYWORD="ff9782"
SYN_FUNC="98b5fe"
SYN_STRING="a4b462"
SYN_NUMBER="5dc7ea"
SYN_TYPE="e9bb83"
SYN_CONST="d6a1e4"
SYN_PROP="dfbcd5"
SYN_COMMENT="88737e"
SYN_OPERATOR="b7a7af"
SYN_SPECIAL="ca7aed"

# wallpaper gradient stops (dark -> tinted)
WALL0="10050e"; WALL1="20131d"; WALL2="4c2740"; WALL3="472844"
