#!/usr/bin/env bash
# Dusty rose on midnight plum.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="pink"
NVIM_COLORSCHEME="rice-pink"
STARSHIP_PALETTE="pink"

BG="19161f"
BG_DARK="120f17"
BG_HL="2c2834"
FG="d5cddc"
FG_MUTED="978e9e"
ACCENT="dd8b88"
ACCENT_ALT="a695d8"

BLACK="3a3545"        BRIGHT_BLACK="575263"
RED="df8f8c"          BRIGHT_RED="f89f9b"
GREEN="98b36f"        BRIGHT_GREEN="a9c77b"
YELLOW="e5c27c"       BRIGHT_YELLOW="fcd586"
BLUE="9ba1e4"         BRIGHT_BLUE="adb3ff"
MAGENTA="d28fb9"      BRIGHT_MAGENTA="eb9fce"
CYAN="73ccad"         BRIGHT_CYAN="7de1bf"
WHITE="bcb4c3"        BRIGHT_WHITE="e8e2ec"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="85576e"   BORDER_INACTIVE="23202a"
SYN_KEYWORD="e8a58e"
SYN_FUNC="a9b5e3"
SYN_STRING="a3b283"
SYN_NUMBER="8bc6b4"
SYN_TYPE="d6c1a3"
SYN_CONST="cda9cf"
SYN_PROP="d1c1d9"
SYN_COMMENT="807688"
SYN_OPERATOR="afa8b6"
SYN_SPECIAL="a695d8"

# wallpaper gradient stops (dark -> tinted)
WALL0="0a080f"; WALL1="19161f"; WALL2="312737"; WALL3="2d2838"
