#!/usr/bin/env bash
# Amber CRT warmth, faded paper.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="retro"
NVIM_COLORSCHEME="rice-retro"
STARSHIP_PALETTE="retro"

BG="231f15"
BG_DARK="1b170e"
BG_HL="373124"
FG="d6d1c1"
FG_MUTED="989281"
ACCENT="e58b49"
ACCENT_ALT="bba02d"

BLACK="473f2f"        BRIGHT_BLACK="655d4c"
RED="ef8678"          BRIGHT_RED="ff9b8e"
GREEN="91b757"        BRIGHT_GREEN="a2cb62"
YELLOW="ecc159"       BRIGHT_YELLOW="ffd572"
BLUE="ab97f3"         BRIGHT_BLUE="bdacff"
MAGENTA="e583b2"      BRIGHT_MAGENTA="fe93c6"
CYAN="50d2a6"         BRIGHT_CYAN="5ae8b7"
WHITE="beb9aa"        BRIGHT_WHITE="e8e4da"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="8d612c"   BORDER_INACTIVE="2e291d"
SYN_KEYWORD="f1a279"
SYN_FUNC="abb2f0"
SYN_STRING="9bb678"
SYN_NUMBER="73cab8"
SYN_TYPE="dac191"
SYN_CONST="d9a3d2"
SYN_PROP="e2c0ae"
SYN_COMMENT="817a66"
SYN_OPERATOR="b2ad9e"
SYN_SPECIAL="bba02d"

# wallpaper gradient stops (dark -> tinted)
WALL0="130f07"; WALL1="231f15"; WALL2="3b301b"; WALL3="39311b"
