#!/usr/bin/env bash
# Amber CRT warmth, faded paper.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="retro"
NVIM_COLORSCHEME="rice-retro"
STARSHIP_PALETTE="retro"

BG="231f15"
BG_DARK="1b170e"
BG_HL="383122"
FG="d6d1c1"
FG_MUTED="989281"
ACCENT="f68000"
ACCENT_ALT="be9f00"

BLACK="473f2f"        BRIGHT_BLACK="655d4c"
RED="ff7969"          BRIGHT_RED="ff9b8e"
GREEN="8abb24"        BRIGHT_GREEN="9acf31"
YELLOW="f7be00"       BRIGHT_YELLOW="ffd572"
BLUE="ac93ff"         BRIGHT_BLUE="bdacff"
MAGENTA="f772b5"      BRIGHT_MAGENTA="ff92c6"
CYAN="00d7a2"         BRIGHT_CYAN="00edb3"
WHITE="beb9aa"        BRIGHT_WHITE="e8e4da"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="955d03"   BORDER_INACTIVE="2e291c"
SYN_KEYWORD="fc9c6a"
SYN_FUNC="a8b0fe"
SYN_STRING="97b869"
SYN_NUMBER="58cfb8"
SYN_TYPE="e1bf7e"
SYN_CONST="e19dd8"
SYN_PROP="e6bfaa"
SYN_COMMENT="817a66"
SYN_OPERATOR="b2ad9e"
SYN_SPECIAL="be9f00"

# wallpaper gradient stops (dark -> tinted)
WALL0="130f07"; WALL1="231f15"; WALL2="4b3815"; WALL3="453a1b"
