#!/usr/bin/env bash
# Catppuccin Mocha. Soft pastels on warm dark grey.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="cozy"
NVIM_COLORSCHEME="catppuccin-mocha"
STARSHIP_PALETTE="cozy"

BG="1e1e2e"
BG_DARK="181825"
BG_HL="313244"
FG="cdd6f4"
FG_MUTED="a6adc8"
ACCENT="cba6f7"
ACCENT_ALT="89b4fa"

BLACK="45475a"        BRIGHT_BLACK="585b70"
RED="f38ba8"          BRIGHT_RED="f38ba8"
GREEN="a6e3a1"        BRIGHT_GREEN="a6e3a1"
YELLOW="f9e2af"       BRIGHT_YELLOW="f9e2af"
BLUE="89b4fa"         BRIGHT_BLUE="89b4fa"
MAGENTA="f5c2e7"      BRIGHT_MAGENTA="f5c2e7"
CYAN="94e2d5"         BRIGHT_CYAN="94e2d5"
WHITE="bac2de"        BRIGHT_WHITE="b4befe"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="7c6da3"   BORDER_INACTIVE="28293a"
SYN_KEYWORD="ef9f9c"
SYN_FUNC="99b9e9"
SYN_STRING="7bbb9f"
SYN_NUMBER="7cc4d7"
SYN_TYPE="e0bd9f"
SYN_CONST="c6aadd"
SYN_PROP="c8c7ef"
SYN_COMMENT="76798c"
SYN_OPERATOR="aab1cd"
SYN_SPECIAL="89b4fa"

# wallpaper gradient stops (dark -> tinted)
WALL0="11111b"; WALL1="1e1e2e"; WALL2="2f2a4a"; WALL3="222c4f"
