#!/usr/bin/env bash
# Mossy greens, warm wood light.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="forest"
NVIM_COLORSCHEME="rice-forest"
STARSHIP_PALETTE="forest"

BG="273030"
BG_DARK="1f2727"
BG_HL="374445"
FG="dad4c4"
FG_MUTED="989281"
ACCENT="8eb367"
ACCENT_ALT="45b7a4"

BLACK="425454"        BRIGHT_BLACK="607374"
RED="e09172"          BRIGHT_RED="faa17f"
GREEN="80b97a"        BRIGHT_GREEN="8ece88"
YELLOW="d6ca76"       BRIGHT_YELLOW="ebdd80"
BLUE="62b1e3"         BRIGHT_BLUE="6dc5fc"
MAGENTA="e08ba1"      BRIGHT_MAGENTA="f99ab3"
CYAN="5ccebe"         BRIGHT_CYAN="63e3d2"
WHITE="c1bfb0"        BRIGHT_WHITE="ece8dd"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="4e7f61"   BORDER_INACTIVE="303b3b"
SYN_KEYWORD="e0ac77"
SYN_FUNC="83c2d9"
SYN_STRING="94b68a"
SYN_NUMBER="7fc7c1"
SYN_TYPE="cdc59f"
SYN_CONST="a9b5e6"
SYN_PROP="e3c1bc"
SYN_COMMENT="817a66"
SYN_OPERATOR="b4b5a6"
SYN_SPECIAL="45b7a4"

# wallpaper gradient stops (dark -> tinted)
WALL0="161f1f"; WALL1="273030"; WALL2="2e4441"; WALL3="2e4343"
