#!/usr/bin/env bash
# Mossy greens, warm wood light.
# GENERATED by theme-palette from seed.sh — edit the seed, not this.
THEME_NAME="forest"
NVIM_COLORSCHEME="rice-forest"
STARSHIP_PALETTE="forest"

BG="273030"
BG_DARK="1f2727"
BG_HL="354445"
FG="dad4c4"
FG_MUTED="989281"
ACCENT="80b930"
ACCENT_ALT="00bba4"

BLACK="425454"        BRIGHT_BLACK="607374"
RED="f88253"          BRIGHT_RED="ff9e79"
GREEN="67c060"        BRIGHT_GREEN="75d56d"
YELLOW="ddca37"       BRIGHT_YELLOW="f3dd40"
BLUE="1ab3fe"         BRIGHT_BLUE="69c5ff"
MAGENTA="f6799e"      BRIGHT_MAGENTA="ff96b3"
CYAN="00d4c0"         BRIGHT_CYAN="00e9d4"
WHITE="c1bfb0"        BRIGHT_WHITE="ece8dd"

# derived roles: soft focus border + nvim syntax
BORDER_ACTIVE="2f8557"   BORDER_INACTIVE="2f3b3b"
SYN_KEYWORD="eba75f"
SYN_FUNC="67c6e5"
SYN_STRING="8bba7c"
SYN_NUMBER="60ccc5"
SYN_TYPE="d2c589"
SYN_CONST="a3b3f8"
SYN_PROP="e9bfb8"
SYN_COMMENT="817a66"
SYN_OPERATOR="b4b5a6"
SYN_SPECIAL="00bba4"

# wallpaper gradient stops (dark -> tinted)
WALL0="161f1f"; WALL1="273030"; WALL2="255149"; WALL3="2c4e4d"
